import { Cpu, FileText } from 'lucide-react';

interface ThreatReportProps {
  report: string[];
  isLoading: boolean;
}

export default function ThreatReport({ report, isLoading }: ThreatReportProps) {
  return (
    <div className="glass-panel p-6 rounded-lg border border-[var(--color-cyber-border)] h-full flex flex-col">
      <div className="flex items-center space-x-2 mb-6 border-b border-[var(--color-cyber-border)] pb-4">
        <Cpu className="h-5 w-5 text-[var(--color-cyber-accent)]" />
        <h2 className="text-lg font-mono font-bold text-white">AI THREAT INTELLIGENCE REPORT</h2>
      </div>

      <div className="flex-1">
        {isLoading ? (
          <div className="flex flex-col items-center justify-center h-full space-y-4 py-8">
            <Cpu className="h-8 w-8 text-[var(--color-cyber-accent)] animate-pulse" />
            <p className="font-mono text-sm text-[var(--color-cyber-muted)]">
              Analyzing attacker behavior with AI...
            </p>
          </div>
        ) : (
          <ul className="space-y-4">
            {report.map((item, index) => (
              <li key={index} className="flex items-start space-x-3 text-sm">
                <div className="mt-0.5">
                  <div className="w-2 h-2 rounded-full bg-[var(--color-cyber-accent)] shadow-[0_0_8px_var(--color-cyber-accent)]"></div>
                </div>
                <p className="text-[var(--color-cyber-text)] leading-relaxed font-sans">
                  {item}
                </p>
              </li>
            ))}
            {report.length === 0 && (
              <li className="text-center text-[var(--color-cyber-muted)] font-mono py-8">
                No intelligence reports generated yet.
              </li>
            )}
          </ul>
        )}
      </div>

      <div className="mt-6 pt-4 border-t border-[var(--color-cyber-border)] flex items-center justify-between">
        <div className="flex items-center text-xs text-[var(--color-cyber-muted)] font-mono">
          <FileText className="h-3 w-3 mr-1" />
          Generated by Gemini AI
        </div>
        <div className="flex items-center text-xs font-mono text-[var(--color-cyber-primary)]">
          <div className="w-1.5 h-1.5 rounded-full bg-[var(--color-cyber-primary)] mr-1.5 animate-pulse"></div>
          Live Sync
        </div>
      </div>
    </div>
  );
}
